MSVC assembly fixups/cleanups
CookiePLMonster/SilentPatch pull request #113
Opened 2024-11-12 21:36 UTC by TheComputerGuy96

This is a separate MR based on a suggestion in https://github.com/CookiePLMonster/SilentPatch/pull/95#issuecomment-2470023367

2024-11-13 11:59 UTC, CookiePLMonster requested changes

2024-11-13 11:59 UTC, CookiePLMonster commented on SilentPatchIII/SilentPatchIII.cpp
> +			call	offset WorldRemove
This is probably wrong.

2024-11-13 12:16 UTC, TheComputerGuy96 commented on SilentPatchIII/SilentPatchIII.cpp
> +			call	offset WorldRemove
That's what syntax I'm using in the GCC inline assembly statement (I can change that if MASM complains)

2024-11-13 12:18 UTC, CookiePLMonster commented on SilentPatchIII/SilentPatchIII.cpp
> +			call	offset WorldRemove
I mean that the call is supposed to dereference `WorldRemove` and call that, `call offset` will probably attempt to call the address of this variable.

2024-11-13 19:22 UTC, TheComputerGuy96 commented on SilentPatchIII/SilentPatchIII.cpp
> +			call	offset WorldRemove
That `offset` keyword introduces run-time issues in GTA 3 (I got a segfault in a user callback on Wine) so I'm definitely removing it

2024-11-14 10:05 UTC, CookiePLMonster commented
Looks good overall, I'll give it a spin next time I am working on SP.

2024-11-18 17:46 UTC, CookiePLMonster approved these changes
Tested all 3 games, looks all good now. Is this fine to squash into a single commit?

2024-11-18 18:30 UTC, TheComputerGuy96 commented
@CookiePLMonster The SA part should probably be left unsquashed (because it's relatively big)

2024-11-18 18:32 UTC, CookiePLMonster commented
OK, I see the review fix was force pushed, so even unsquashed history is clean. Fine by me then.

2024-11-18 18:33 UTC, merged